### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by fvieir** [Gabriel-L-Santos/site-de-compras-ctd#1]
Fala Gabriel.

Conforme deixado o Feedback e orientações no Discord, segue minhas solicitação para entrega do deploy.

Para deploy você pode usar o netlify, mas sinta-se livre para usar outras plataformas.

Qualquer duvida é so chamar.

Forte abraço.

**Comment by Gabriel-L-Santos** [comment]
Fala Fabrício.

Já fiz o meu primeiro deploy no netlify: https://bar-be-aria-alura.netlify.app/

Vou fazer também dos meus outros projetos.

Obrigado pela dica!

Abraços!
