### ISSUE TITLE
Estrtutura das pastas

### ISSUE THREAD

**Issue by fvieir** [Gabriel-L-Santos/site-de-compras-ctd#2]
Olá Gabriel.

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para estrtutura das pastas.

Segue uma ideia de como estruturar as pastas.

![image](https://user-images.githubusercontent.com/65264206/196414235-35e7d046-da1a-42d8-8206-bbc0b86641af.png)

Qualquer duvida é so chamar.

**Comment by Gabriel-L-Santos** [comment]
Fala Fabrício, obrigado pela sugestão, vou estruturar os meus próximos projetos a partir de agora dessa maneira, por enquanto eu estou focado no terceiro projeto, mas vou arrumar as pastas deste projeto em breve.

Abraços!
